sudo: required
services:
 - docker

before_install:
 - docker build -t agremond/react-test -f ./client/Dockerfile.dev ./client
  
script:
 - docker run agremond/react-test npm test -- --coverage

after_sucess:
 - docker build -t agremond/multi-client ./client
 - docker build -t agremond/multi-nginx ./nginx
 - docker build -t agremond/multi-server ./server
 - docker build -t agremond/multi-worker ./worker
#Login into docker CLI

 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

#Take those images and push them to docker hub

 - docker push agremond/multi-client
 - docker push agremond/multi-nginx
 - docker push agremond/multi-server
 - docker push agremond/multi-worker

