---
version: '3'
services:
 postgres:
  image: 'postgres:10'
  env_file:
   - api.env
  ports:
   - '5432:5432'
 redis:
  image: 'redis:latest'
 api:
  build:
   dockerfile: Dockerfile.dev
   context: ./server
  volumes:
   - /app/node_modules
   - ./server:/app
  env_file:
   - api.env
 client:
  build:
   dockerfile: Dockerfile.dev
   context: ./client
  volumes:
   - /app/node_modules
   - ./client:/app
 worker:
  build:
   dockerfile: Dockerfile.dev
   context: ./worker
  volumes:
   - /app/node_modules
   - ./worker:/app
 nginx:
  restart: always
  build:
   dockerfile: Dockerfile.dev
   context: ./nginx
  ports:
   - '3050:80' 
